import type { Metadata } from 'next'

import { MobileScreen } from '../components/mobile-screen'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <MobileScreen>{children}</MobileScreen>
      </body>
    </html>
  )
}
